language: java
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_b56aed2a0871_key -iv $encrypted_b56aed2a0871_iv
  -in api-client-secret.json.enc -out api-client-secret.json -d
- chmod +x mvnw
script: mvn clean install
jdk:
- openjdk8
deploy:
  provider: gae
  keyfile: api-client-secret.json.enc
  project: perisdev
